<h1>Proveedor > Modificar Proveedor</h1>
<p>Este modulo le permitira modificar un proveedor de la empresa, rellene muy bien los campos para no realizar una inserción erronea.</p>
<p>Ingrese el nit del proveedor que desea Modificar.</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/prooveedor/modifica',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('nit');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>

<?php
	echo $this->form()->closeTag();
?>
</div >
<div id="tablaRegistro">
	Mostrar formulario de modificar
</div>