<h1>Producto > Agregar Producto</h1>
<p>Este modulo le permitira agregar un Producto de la empresa, rellene muy bien los campos para no realizar una inserción erronea</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/producto/agrega',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('referencia');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php 
	$select=$form->get('categoria');
	echo $formLabel->openTag().$select->getLabel();
	echo $formLabel->closeTag();
	echo $this->formSelect($select);
	echo $this->formElementErrors($select);
?>
</div>

<div>
<?php
    $name = $form->get('precioProducto');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('existencia');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>


<?php
	echo $this->form()->closeTag();
?>
</div >

<div id="tablaRegistro">
    <table border="1" >
    <caption>Productos Registrados</caption>
        <thead>
            <th>Referencia</th>
            <th>Categoria</th>
            <th>Precio</th>
            <th>Existencia</th>
        </thead>
         <tbody>
            <?php foreach ($this->datos as $dato){ ?>
        <tr style="background-color:<?php echo $this->cycle(array("#008FFF","#F8B161"))->next()?>">

            <td><?php echo $dato["Referencia_producto"] ?></td>
            <td><?php echo $dato["Categoria_Id_Categoria"] ?></td>
            <td><?php echo $dato["Precio_producto"] ?></td>
            <td><?php echo $dato["Existencia_producto"] ?></td>
        </tr>
    <?php } ?>

    <?php
    $this->cycle()->assign(array("#008FFF", "#F8B161"));
    $this->cycle()->prev();
    ?>
        </tbody>
    </table>
</div>

<?php
    if(!empty($this->respuesta))
    {
        ?>
        <p><?php echo $this->respuesta; ?></p>
        <?php
    }
?>