<h1>Producto > Surtir Producto</h1>
<p>Este modulo le permitira modificar un Producto de la empresa, rellene muy bien los campos para no realizar una eliminacion erronea.</p>
<p>Ingrese el Nit del Producto a modificar.</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/producto/modifica',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('nit');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>

<?php
	echo $this->form()->closeTag();
?>
</div >
<div id="tablaRegistro">
	mostrar formulario de modificar
</div>