<h1>Empleado > Agregar Empleado</h1>
<p>Este modulo le permitira agregar un Empleado de la empresa, rellene muy bien los campos para no realizar una inserción erronea</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/empleado/agrega',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('nit');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('apellido');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('telefono');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('direccion');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>


<?php
	echo $this->form()->closeTag();
?>
</div >
<?php
    if(!empty($this->respuesta))
    {
        ?>
        <p><?php echo $this->respuesta; ?></p>
        <?php
    }
 ?>