<h1>Empleado > Eliminar Empleado</h1>
<p>Este modulo le permitira eliminar un empleado de la empresa, rellene muy bien los campos para no realizar una eliminacion erronea.</p>
<p>Ingrese el Nit del empleado a eliminar.</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/empleado/elimina',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('nit');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>

<?php
	echo $this->form()->closeTag();
?>
</div >
<div id="tablaRegistro">
	mostrar letrero de exito
</div>