<h1>Cliente > Agregar Cliente</h1>
<p>Este modulo le permitira agregar un Cliente de la empresa, rellene muy bien los campos para no realizar una inserción erronea.</p>
<div id="formRegistro">
<?php 
	$form=$this->form;
	$form->prepare();
	$form->setAttributes(array(
				'action'=>$this->url.'/cliente/agrega',
				'method'=>'post',
			));
	$formLabel=$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>

<div>
<?php
    $name = $form->get('nit');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('apellido');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('telefono');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $name = $form->get('direccion');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>

<div>
<?php
    $envia = $form->get('btnSubmit');
    echo $this->formInput($envia);
    echo $formLabel->closeTag();
?>
</div>
<?php
	echo $this->form()->closeTag();
?>
</div >
<div id="tablaRegistro">
    <table border="1" >
    <caption>Clientes Registrados</caption>
        <thead>
            <th>Identificacion</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Telefono</th>
            <th>Direccion</th>
        </thead>
         <tbody>
            <?php foreach ($this->datos as $dato){ ?>
        <tr style="background-color:<?php echo $this->cycle(array("#008FFF","#F8B161"))->next()?>">

            <td><?php echo $dato["Nit_cliente"] ?></td>
            <td><?php echo $dato["Nombre_cliente"] ?></td>
            <td><?php echo $dato["Apellido_cliente"] ?></td>
            <td><?php echo $dato["Telefono_cliente"] ?></td>
            <td><?php echo $dato["Direccion_cliente"] ?></td>
        </tr>
    <?php } ?>

    <?php
    $this->cycle()->assign(array("#008FFF", "#F8B161"));
    $this->cycle()->prev();
    ?>
        </tbody>
    </table>
</div>
<?php
    if(!empty($this->respuesta))
    {
        ?>
        <p><?php echo $this->respuesta; ?></p>
        <?php
    }
?>