<h1>Cliente > Modificar Cliente</h1>
<p>Este modulo le permitira modificar un Cliente de la empresa, rellene muy bien los campos para no realizar una inserción erronea.</p>
<p>Ingrese el nit del Cliente que desea Modificar.</p>
<div id="formRegistro">
	<?php 
		$form=$this->form;
		$form->prepare();
		$form->setAttributes(array(
					'action'=>$this->url.'/cliente/modifica',
					'method'=>'post',
				));
		$formLabel=$this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>

	<div>
	<?php
	    $name = $form->get('busqueda');
	    echo $formLabel->openTag() . $name->getOption('label');
	    echo $formLabel->closeTag();
	    echo $this->formInput($name);
	?>
	</div>
	<div>
	<?php
	    $envia = $form->get('btnSubmit');
	    echo $this->formInput($envia);
	    echo $formLabel->closeTag();
	?>
	</div>
	<div>
	<?php
		echo $this->form()->closeTag();
	?>
	</div>
</div>
<div id="tablaRegistro">
<?php echo $this->mensaje; ?>
<?php echo $this->nativo; ?>
</div>

